apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://victoriametrics:8428
    isDefault: false
    editable: false
    jsonData:
      timeInterval: '10s'
